In [2]:
import numpy as np

In [42]:
lst = [1,2,3,4,5,6,7,8,9]
lst[0:5]

[1, 2, 3, 4, 5]

In [4]:
arr = np.array(lst)

In [46]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz[1:3,0:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [41]:
matriz[:6]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [91]:
num = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]],[[21,22,23],[24,25,26],[27,28,29],[30,31,32]]
num = np.array(num, dtype='float64')
num.dtype

dtype('float64')

In [348]:
num[0:1,0:2,-1]

array([[3., 6.]])

In [100]:
scalar = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(scalar)
scalar.ndim

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


3

In [103]:
vector = np.array([1,2,3], ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [110]:
print(vector, vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


In [113]:
np.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [117]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [121]:
np.linspace(0,100,50)
# (inicio,final,numero de datos)

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [122]:
# alhebra
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [133]:
np.random.rand(4,4,4)

array([[[[0.76174039, 0.17704541, 0.23833214, 0.32974588],
         [0.56288215, 0.17196117, 0.18204825, 0.44476137],
         [0.69539565, 0.05970841, 0.89003874, 0.01180779],
         [0.53467035, 0.83241502, 0.21737164, 0.87300623]],

        [[0.65886681, 0.50421931, 0.21955062, 0.93182225],
         [0.50518638, 0.9834709 , 0.07821667, 0.07976822],
         [0.2742066 , 0.30217112, 0.68823344, 0.61648849],
         [0.29715873, 0.09577113, 0.48653263, 0.11617077]],

        [[0.79747443, 0.02683086, 0.96908225, 0.72063274],
         [0.20731611, 0.88058774, 0.27850382, 0.08371288],
         [0.41311445, 0.12965212, 0.03532767, 0.96631008],
         [0.462974  , 0.4009613 , 0.98951019, 0.03116272]],

        [[0.32900352, 0.57428949, 0.83377506, 0.3483385 ],
         [0.13527401, 0.96452854, 0.79388001, 0.46882903],
         [0.226058  , 0.34611571, 0.98296091, 0.61648588],
         [0.85338615, 0.22364907, 0.54435014, 0.12865493]]],


       [[[0.44753364, 0.66094234, 0.23458709, 

In [135]:
#definir los pesos de una red neuronal 
np.random.randint(1,15)

6

In [145]:
#valores enteros de 1 a 100 con una estructora de 10 x 10 
np.random.randint(1,100,(5,5))

array([[14, 67,  3, 91, 30],
       [93, 15, 68,  2, 86],
       [65, 17, 29, 95, 91],
       [43, 92, 56, 93, 30],
       [ 7, 93, 16, 52, 21]])

In [160]:
#                       (desde 1,hasta 10,(dimensiones,numero de filas, datos por fila)
arr = np.random.randint(1,10,(2,3,4))
print(arr)

[[[1 4 7 9]
  [4 2 7 3]
  [9 8 6 1]]

 [[3 9 1 2]
  [3 4 1 6]
  [8 7 3 6]]]


In [161]:
#me dice cuantas cantidades tengo por cada una de las dimensiones 
arr.shape

(2, 3, 4)

In [166]:
#Cambiar la forma que tengo establecida en un array  
# (dimensiones,numero de filas, datos por fila)
arr.reshape(4,3,2)

array([[[1, 4],
        [7, 9],
        [4, 2]],

       [[7, 3],
        [9, 8],
        [6, 1]],

       [[3, 9],
        [1, 2],
        [3, 4]],

       [[1, 6],
        [8, 7],
        [3, 6]]])

In [167]:
#el mismo reshape pero con diferete forma de esribirlo 
np.reshape(arr,(1,24))

array([[1, 4, 7, 9, 4, 2, 7, 3, 9, 8, 6, 1, 3, 9, 1, 2, 3, 4, 1, 6, 8, 7,
        3, 6]])

In [169]:
#organizar de acuerdo a lenguaje C
np.reshape(arr,(4,3,2),'C')

array([[[1, 4],
        [7, 9],
        [4, 2]],

       [[7, 3],
        [9, 8],
        [6, 1]],

       [[3, 9],
        [1, 2],
        [3, 4]],

       [[1, 6],
        [8, 7],
        [3, 6]]])

In [170]:
#organizar de acuerdo a lenguaje FORTRAN
np.reshape(arr,(4,3,2),'F')

array([[[1, 7],
        [9, 6],
        [2, 3]],

       [[3, 1],
        [8, 3],
        [4, 6]],

       [[4, 7],
        [4, 9],
        [8, 1]],

       [[3, 1],
        [9, 2],
        [7, 6]]])

In [171]:
#organizar de acuerdo a lenguaje del sistema operatico de mi PC
np.reshape(arr,(4,3,2),'A')

array([[[1, 4],
        [7, 9],
        [4, 2]],

       [[7, 3],
        [9, 8],
        [6, 1]],

       [[3, 9],
        [1, 2],
        [3, 4]],

       [[1, 6],
        [8, 7],
        [3, 6]]])

FUNCIONES PRINCIPALES DE NUMPY 

In [179]:
arr1 = np.random.randint(1,20,10)
arr1

array([ 7, 12, 13, 12,  9, 12, 18,  3,  6, 14])

In [181]:
matriz1 = arr1.reshape(2,5)
matriz1

array([[ 7, 12, 13, 12,  9],
       [12, 18,  3,  6, 14]])

In [189]:
#MAX traer el numero mas grande del array 
# arr1.max()
matriz1.max(0)

array([12, 18, 13, 12, 14])

In [191]:
#ARG MAX() nos muestra el indice donde se encuentra el valor mas grande en el array 
arr1.argmax()

6

In [194]:
matriz1.argmax(0)

array([1, 1, 0, 0, 1])

In [197]:
arr1.min()
matriz1.min(1)

array([7, 3])

In [198]:
#la distacina del valor minimo al valor maximo 
arr1.ptp()

15

In [200]:
matriz1.ptp(0)

array([ 5,  6, 10,  6,  5])

In [202]:
#PERCENTIL 50 es la mitad, PERCENTIL 0 es el numero menor, PERCENTIL 100 es el numero mayor 
np.percentile(arr1,50)

12.0

In [203]:
#MEDIANA es el percentil 50, donde se encuentra la mitad de mis datos 
np.median(arr1)
np.median(matriz,1)

12.0

In [204]:
#DESVIACION ESTANDARD 
np.std(arr1)

4.1521078984053394

In [205]:
#VARIANZA
np.var(arr1)

17.240000000000002

In [ ]:
#MEDIA la suma de todos los valores dividida por el numero de valores 
np.mean(arr1)

In [206]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])

In [208]:
np.concatenate((a,b),axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [210]:
#Check the number of dimentios 
a.ndim
b.ndim      

1

In [211]:
#reshape dimentions 
b = np.expand_dims(b,axis=0)
b.ndim

2

In [212]:
#Now that I have all variables with the same dimentions I can concat it 
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [213]:
b

array([[5, 6]])

In [214]:
#TRANSPUESTA DE UNA MATRIS → CAMBIARLE LA FORMA 
b.T

array([[5],
       [6]])

In [ ]:
#.copy() nos permite copiar un array de NumPy en otra variable de tal forma que al modificar el nuevo array los cambios no se vean reflejados en array original.
#Siempre usarel comando COPY primero antes de hacer calculos para no dañar el arrayoriginal
arr_copy = arr.copy()

In [215]:
#CONDICIONES 
arr2 = np.linspace(1,10,10, dtype='int8')
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [217]:
indices_condicion = arr2 > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [219]:
arr3 = np.arange(0,10)
arr4 = arr3.copy()

In [220]:
#OPERACIONES 
arr4 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [221]:
11/ arr4

<ipython-input-221-b776d39c69fd>:1: RuntimeWarning: divide by zero encountered in true_divide
  11/ arr4


array([        inf, 11.        ,  5.5       ,  3.66666667,  2.75      ,
        2.2       ,  1.83333333,  1.57142857,  1.375     ,  1.22222222])

#PRODUCTO PUNTO 

In [238]:
var1 = np.array([[0,3,5],[5,5,2]])
var1

array([[0, 3, 5],
       [5, 5, 2]])

In [240]:
var2 = np.array([[3,4],[3,-2],[4,-2]])
var2

array([[ 3,  4],
       [ 3, -2],
       [ 4, -2]])

In [260]:
var1.T * var2

array([[  0,  20],
       [  9, -10],
       [ 20,  -4]])

In [254]:
nuevo = np.random.randint(10,100,(5,5))
nuevo

array([[20, 11, 52, 63, 96],
       [86, 83, 82, 82, 81],
       [16, 36, 65, 69, 96],
       [45, 61, 51, 21, 84],
       [31, 44, 80, 97, 56]])

************ BORRAR ********

In [272]:
col = np.arange(1,10)
col

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

※※※※※※※※※※※ PANDAS ※※※※※※※※※※※

In [273]:
import pandas as pd

In [277]:
psg_players = pd.Series(['Navas','Mbappe','Neymar','Messi'],index=[1,7,10,30]
)
psg_players

1      Navas
7     Mbappe
10    Neymar
30     Messi
dtype: object

In [349]:
dic = {1:"Navas", 7:"MBape", 10:"Neymar", 30:"Messi"}
pd.Series(dic)


1      Navas
7      MBape
10    Neymar
30     Messi
dtype: object

In [285]:
#El indice no funciona como en la python normal sino como el numero exacto del dato MBape tiene numero 7
dic[7]

#Sin embargo si quiero hacer slicing si debo hacerlo desde la posicion 0 hasta la maxima +1 que se encuentre 
psg_players[0:3]

1      Navas
7      MBape
10    Neymar
dtype: object

In [350]:
dict = {'Jugador':['Navas','MBappe','Neymar','Messi'],
         'Altura': [183.0,170.0,170.0,165.0],
          'Goles': [2,200,200,200]
}

In [351]:
equipo = pd.DataFrame(dict,index=[8,80,800,8000])

In [352]:
equipo.columns[0]

'Jugador'

In [295]:
equipo.index[0]

8

＊＊＊＊＊＊＊＊LEER ARCHIVOS＊＊＊＊＊＊

In [354]:
books = pd.read_csv('/Users/javi/Desktop/bestsellers-with-categories.csv', sep=',')
books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [344]:
pd.read_json('/Users/javi/Desktop/hpcharactersdataraw.json')

Name                                               Link  \
0              Mrs. Abbott  https://www.hp-lexicon.org/character/abbott-fa...   
1            Hannah Abbott  https://www.hp-lexicon.org/character/abbott-fa...   
2            Abel Treetops  https://www.hp-lexicon.org/character/abel-tree...   
3         Euan Abercrombie  https://www.hp-lexicon.org/character/abercromb...   
4     Aberforth Dumbledore  https://www.hp-lexicon.org/character/dumbledor...   
...                    ...                                                ...   
1935        Georgi Zdravko  https://www.hp-lexicon.org/character/georgi-zd...   
1936                Zograf       https://www.hp-lexicon.org/character/zograf/   
1937                 Zonko        https://www.hp-lexicon.org/character/zonko/   
1938     Valentina Vázquez  https://www.hp-lexicon.org/character/valentina...   
1939         Zygmunt Budge  https://www.hp-lexicon.org/character/zygmunt-b...   

                                                  Descr  Gender Species/Race  \
0     Mrs. Abbott was the mother of Hannah Abbott, a...  Female        Witch   
1     Hannah Abbott is a Hufflepuff student in Harry...  Female        Witch   
2     Abel Treetops was a wizard from Cincinnati who...    Male       Wizard   
3     Euan Abercrombie was a small boy with prominen...    Male       Wizard   
4     Aberforth Dumbledore was a tall, thin, grumpy-...    Male       Wizard   
...                                                 ...     ...          ...   
1935  Georgi Zdravko played Keeper for the Bulgarian...    Male       Wizard   
1936  Zograf played Keeper for the Bulgarian Nationa...     NaN       Wizard   
1937  Founder(?) of Zonko’s Joke Shop. Possibly a re...     NaN      Unknown   
1938  Valentina Vázquez was President of the Argenti...  Female        Witch   
1939  Zygmunt Budge is considered to be one of the m...    Male       Wizard   

            Blood                 School  \
0     Muggle-born                Unknown   
1      Half-blood  Hogwarts - Hufflepuff   
2         Unknown                Unknown   
3         Unknown  Hogwarts - Gryffindor   
4      Half-blood     Hogwarts - Student   
...           ...                    ...   
1935      Unknown                Unknown   
1936      Unknown                Unknown   
1937      Unknown                Unknown   
1938      Unknown                Unknown   
1939      Unknown     Hogwarts - Student   

                                         Profession  
0                                           Unknown  
1                    Landlady of the Leaky Cauldron  
2                                           Unknown  
3                                           Unknown  
4                                            Barman  
...                                             ...  
1935                      Quidditch player (Seeker)  
1936                      Quidditch player (Keeper)  
1937                                        Unknown  
1938  President of the Argentinian Council of Magic  
1939    Potions Master, Potioneer, Inventor, Author  

[1940 rows x 8 columns]

In [312]:
books.loc[:10,['Reviews']] 

Reviews
0    -17350
1     -2052
2    -18979
3    -21424
4     -7665
5    -12643
6    -19735
7    -19699
8     -5983
9    -23848
10   -23848

In [322]:
books.iloc[3:5,:4]

Name  \
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                     Author  User Rating  Reviews  
3             George Orwell          4.7    21424  
4  National Geographic Kids          4.8     7665

In [323]:
#Me retorna el numero de lineas que le pida 
books.head(2)

Name        Author  User Rating  Reviews  Price  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8   
1              11/22/63: A Novel  Stephen King          4.6     2052     22   

   Year        Genre  
0  2016  Non Fiction  
1  2011      Fiction

＊＊＊＊＊＊＊＊　DROP COLUMS ＊＊＊＊＊＊＊＊

In [332]:
#borrar una columna pero solo en el resultado 
books.drop('Genre', axis=1).head(2)

Name        Author  User Rating  Reviews  Price  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8   
1              11/22/63: A Novel  Stephen King          4.6     2052     22   

   Year  
0  2016  
1  2011

In [333]:
#Borrar una columna definitiva, axis 1 es columnas
books.drop('Genre', axis=1,inplace=True)

Name        Author  User Rating  Reviews  Price  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8   
1              11/22/63: A Novel  Stephen King          4.6     2052     22   

   Year        Genre  
0  2016  Non Fiction  
1  2011      Fiction

In [355]:
#Borrar una fila, 0 es para filas 
books.drop(0, axis =0).head(2)

Name              Author  User Rating  \
1                        11/22/63: A Novel        Stephen King          4.6   
2  12 Rules for Life: An Antidote to Chaos  Jordan B. Peterson          4.7   

   Reviews  Price  Year        Genre  
1     2052     22  2011      Fiction  
2    18979     15  2018  Non Fiction

＊＊＊＊＊＊＊＊　ADD COLUMNS ＊＊＊＊＊＊＊＊

In [334]:
books.head(2)

Name        Author  User Rating  Reviews  Price  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8   
1              11/22/63: A Novel  Stephen King          4.6     2052     22   

   Year        Genre  
0  2016  Non Fiction  
1  2011      Fiction

In [356]:
#Crear nueva columna
books['New column'] = np.nan

In [359]:
#creamos nuevos valores y los guardamos en la variable data
data = np.arange(0,books.shape[0])
data

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [358]:
#agregamos la nuevacolumna y le pasamos los valores que hay en la variable data despues del signo =
books['Range'] = data

＊＊＊＊＊＊＊＊　ADD ROWS (FILAS) ＊＊＊＊＊＊＊＊

In [360]:
books.append(books)
books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  \
0                    JJ Smith          4.7    17350      8  2016  Non Fiction   
1                Stephen King          4.6     2052     22  2011      Fiction   
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction   
3               George Orwell          4.7    21424      6  2017      Fiction   
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction   
..                        ...          ...      ...    ...   ...          ...   
545               Jeff Kinney          4.9     9413      8  2019      Fiction   
546               Jen Sincero          4.7    14331      8  2016  Non Fiction   
547               Jen Sincero          4.7    14331      8  2017  Non Fiction   
548               Jen Sincero          4.7    14331      8  2018  Non Fiction   
549               Jen Sincero          4.7    14331      8  2019  Non Fiction   

     New column  Range  
0           NaN      0  
1           NaN      1  
2           NaN      2  
3           NaN      3  
4           NaN      4  
..          ...    ...  
545         NaN    545  
546         NaN    546  
547         NaN    547  
548         NaN    548  
549         NaN    549  

[550 rows x 9 columns]

In [366]:
dataica = np.array([2,2])
dataica

array([2, 2])